runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /js
  static_dir: js

- url: /assets
  static_dir: assets

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /.*   # this grabs every other relative url not specified above
  script: server.app